### ISSUE TITLE
Implement GPT-4

### ISSUE THREAD

**Issue by peterjaap** [SamueleMartini/Magento-GPT-integration#1]

**Comment by SamueleMartini** [comment]
@peterjaap Thank you for your suggestion.
Thank you for your suggestion.

I think the module should be reviewed, changing the name from GTP**3** to just "GPT", so that it can be updated over time following the evolutions and versions of the language model without being tied to a specific version.

The module connects via API, so GPT-4 should be usable by simply choosing the right "model" from the configurations in the Magento admin panel, but I've never tested it.

**Comment by peterjaap** [comment]
@SamueleMartini awesome, thanks! Yeah renaming it might make the most sense. Maybe to "Magento-OpenAI-integration" or something even more generic like "Magento-AI-integration"?
